"""empty message

Revision ID: 437d866d041f
Revises: b1ea87575ef6
Create Date: 2022-05-18 13:25:00.715694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437d866d041f'
down_revision = 'b1ea87575ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL')

    op.alter_column('todos', 'completed', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
